import type { Plan } from "@/lib/plans";

export type ServiceCategory =
  | "Advertising"
  | "Email & SMS"
  | "SEO"
  | "Content"
  | "Social Growth"
  | "Other";

export type Service = {
  id: string;
  name: string;
  category: ServiceCategory;
  description: string;
  requiredPlan: Plan;
  aiEnabled: boolean;
  icon: string;
  href: string;
};

const socialPlatforms = [
  "TikTok",
  "LinkedIn",
  "Twitter",
  "Instagram",
  "Facebook",
  "YouTube",
  "Discord",
  "Spotify",
  "Telegram",
  "Reddit",
  "Clubhouse",
  "Threads",
  "Twitch",
  "Truth Social",
  "Pinterest",
  "Quora",
] as const;

const socialServices: Service[] = socialPlatforms.map((platform) => ({
  id: `social-${platform.toLowerCase().replace(/\s+/g, "-")}`,
  name: platform,
  category: "Social Growth",
  description: `${platform} growth strategy, outreach, and account acceleration support.`,
  requiredPlan: "starter",
  aiEnabled: false,
  icon: "Users",
  href: "/dashboard/social",
}));

export const SERVICES: Service[] = [
  {
    id: "targeted-mass-dm",
    name: "Targeted Mass DM (up to 2M/day)",
    category: "Advertising",
    description: "High-volume targeted direct message campaigns with audience segmentation.",
    requiredPlan: "growth",
    aiEnabled: false,
    icon: "Send",
    href: "/dashboard/ads",
  },
  {
    id: "digital-ads",
    name: "Digital Ads (all platforms)",
    category: "Advertising",
    description: "Paid ads strategy and execution across multi-channel ad platforms.",
    requiredPlan: "growth",
    aiEnabled: false,
    icon: "Megaphone",
    href: "/dashboard/ads",
  },
  {
    id: "ig-account-outreach",
    name: "IG Account Outreach",
    category: "Advertising",
    description: "Instagram account outreach workflows to drive replies and pipeline.",
    requiredPlan: "starter",
    aiEnabled: false,
    icon: "Instagram",
    href: "/dashboard/ads",
  },
  {
    id: "cold-email-outreach",
    name: "Cold Email Outreach",
    category: "Advertising",
    description: "Cold email setup, campaign infrastructure, and reply optimization.",
    requiredPlan: "starter",
    aiEnabled: true,
    icon: "Mail",
    href: "/dashboard/ads",
  },
  {
    id: "email-sms-flows",
    name: "Email/SMS Flows, Templates & Integrations",
    category: "Email & SMS",
    description: "Lifecycle automations, template systems, and sender stack integrations.",
    requiredPlan: "starter",
    aiEnabled: false,
    icon: "MessageSquare",
    href: "/dashboard/email",
  },
  {
    id: "seo-audit-report",
    name: "Full Scope SEO: Audit Report",
    category: "SEO",
    description: "Comprehensive SEO audit with technical, on-page, and opportunity insights.",
    requiredPlan: "starter",
    aiEnabled: true,
    icon: "Search",
    href: "/dashboard/seo",
  },
  {
    id: "keyword-research",
    name: "Keyword Research",
    category: "SEO",
    description: "Keyword opportunity mapping by intent, difficulty, and revenue potential.",
    requiredPlan: "starter",
    aiEnabled: true,
    icon: "KeyRound",
    href: "/dashboard/seo",
  },
  {
    id: "technical-seo",
    name: "Technical SEO",
    category: "SEO",
    description: "Technical SEO implementation for crawlability, speed, and index health.",
    requiredPlan: "growth",
    aiEnabled: true,
    icon: "Wrench",
    href: "/dashboard/seo",
  },
  {
    id: "onpage-offpage-backlinks",
    name: "On-Page & Off-Page Backlinks",
    category: "SEO",
    description: "On-page optimizations and backlink strategies for authority growth.",
    requiredPlan: "growth",
    aiEnabled: false,
    icon: "Link",
    href: "/dashboard/seo",
  },
  {
    id: "competitor-analysis",
    name: "Competitor Analysis",
    category: "SEO",
    description: "Competitive intelligence covering keyword, content, and backlink gaps.",
    requiredPlan: "growth",
    aiEnabled: true,
    icon: "Radar",
    href: "/dashboard/seo",
  },
  {
    id: "content-distribution",
    name: "Content Distribution (multi-page push)",
    category: "Content",
    description: "Distribution systems to publish and repurpose content across channels.",
    requiredPlan: "starter",
    aiEnabled: false,
    icon: "Share2",
    href: "/dashboard/content",
  },
  {
    id: "content-creation",
    name: "Content Creation (video editing, gifs, explainer videos)",
    category: "Content",
    description: "Creative production for short-form, explainers, GIF content, and edits.",
    requiredPlan: "growth",
    aiEnabled: true,
    icon: "Clapperboard",
    href: "/dashboard/content",
  },
  {
    id: "graphic-design",
    name: "Graphic Design (posts, 3D, logos, flyers)",
    category: "Content",
    description: "Visual design services including social posts, logo work, and flyers.",
    requiredPlan: "growth",
    aiEnabled: false,
    icon: "Palette",
    href: "/dashboard/content",
  },
  ...socialServices,
  {
    id: "web-app-development",
    name: "Web/App Development",
    category: "Other",
    description: "Custom web and app development with product and growth alignment.",
    requiredPlan: "elite",
    aiEnabled: false,
    icon: "Code2",
    href: "/dashboard/community",
  },
  {
    id: "community-dfy-buildout",
    name: "Community DFY Buildout",
    category: "Other",
    description: "Done-for-you community architecture, setup, and launch support.",
    requiredPlan: "elite",
    aiEnabled: false,
    icon: "UsersRound",
    href: "/dashboard/community",
  },
  {
    id: "targeted-data-scraping",
    name: "Targeted Data Scraping",
    category: "Other",
    description: "Custom lead and market dataset extraction with targeting controls.",
    requiredPlan: "growth",
    aiEnabled: false,
    icon: "Database",
    href: "/dashboard/lead-gen",
  },
  {
    id: "ai-services",
    name: "AI Services (chatbots, AI art, AI voiceover)",
    category: "Other",
    description: "AI-enabled production services for bots, visual content, and voice assets.",
    requiredPlan: "growth",
    aiEnabled: true,
    icon: "Bot",
    href: "/dashboard/ai-services",
  },
  {
    id: "consulting",
    name: "Consulting",
    category: "Other",
    description: "Hands-on strategic consulting for growth systems and execution.",
    requiredPlan: "elite",
    aiEnabled: false,
    icon: "Briefcase",
    href: "/dashboard/community",
  },
  {
    id: "dfy-podcast-launch",
    name: "DFY Podcast Launch",
    category: "Other",
    description: "Launch support for podcast planning, production, and distribution.",
    requiredPlan: "growth",
    aiEnabled: false,
    icon: "Mic",
    href: "/dashboard/community",
  },
  {
    id: "dfy-white-label-agency",
    name: "DFY White Label Agency",
    category: "Other",
    description: "Full white-label agency infrastructure and fulfillment operations.",
    requiredPlan: "white_label",
    aiEnabled: false,
    icon: "ShieldCheck",
    href: "/dashboard/community",
  },
  {
    id: "gwu-agency-full-course",
    name: "GWU Agency Full Course (120+ videos)",
    category: "Other",
    description: "End-to-end training curriculum for building and operating agency systems.",
    requiredPlan: "starter",
    aiEnabled: false,
    icon: "GraduationCap",
    href: "/dashboard/community",
  },
];
